---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/sonam1412/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-main-kwbr
